//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T cs_5_0 /O1 /E SimulateHair_B shaders\Source\HairSimulate.hlsl /Fo
//    Shaders\Cache\Object\Release\SimulateHair_B.obj /Fe
//    Shaders\Cache\Error\SimulateHair_B.txt /Fc
//    Shaders\Cache\Assembly\SimulateHair_B.asm
//
//
// Buffer Definitions: 
//
// cbuffer ConstBufferCS_Per_Frame
// {
//
//   row_major float4x4 g_ModelTransformForHead;// Offset:    0 Size:    64 [unused]
//   row_major float4x4 g_ModelPrevInvTransformForHead;// Offset:   64 Size:    64 [unused]
//   float4 g_ModelRotateForHead;       // Offset:  128 Size:    16
//   float4 g_Wind;                     // Offset:  144 Size:    16 [unused]
//   float4 g_Wind1;                    // Offset:  160 Size:    16 [unused]
//   float4 g_Wind2;                    // Offset:  176 Size:    16 [unused]
//   float4 g_Wind3;                    // Offset:  192 Size:    16 [unused]
//   int g_NumLengthConstraintIterations;// Offset:  208 Size:     4 [unused]
//   int g_bCollision;                  // Offset:  212 Size:     4 [unused]
//   float g_GravityMagnitude;          // Offset:  216 Size:     4 [unused]
//   float g_TimeStep;                  // Offset:  220 Size:     4 [unused]
//   float g_Damping0;                  // Offset:  224 Size:     4 [unused]
//   float g_StiffnessForLocalShapeMatching0;// Offset:  228 Size:     4
//   float g_StiffnessForGlobalShapeMatching0;// Offset:  232 Size:     4 [unused]
//   float g_GlobalShapeMatchingEffectiveRange0;// Offset:  236 Size:     4 [unused]
//   float g_Damping1;                  // Offset:  240 Size:     4 [unused]
//   float g_StiffnessForLocalShapeMatching1;// Offset:  244 Size:     4
//   float g_StiffnessForGlobalShapeMatching1;// Offset:  248 Size:     4 [unused]
//   float g_GlobalShapeMatchingEffectiveRange1;// Offset:  252 Size:     4 [unused]
//   float g_Damping2;                  // Offset:  256 Size:     4 [unused]
//   float g_StiffnessForLocalShapeMatching2;// Offset:  260 Size:     4
//   float g_StiffnessForGlobalShapeMatching2;// Offset:  264 Size:     4 [unused]
//   float g_GlobalShapeMatchingEffectiveRange2;// Offset:  268 Size:     4 [unused]
//   float g_Damping3;                  // Offset:  272 Size:     4 [unused]
//   float g_StiffnessForLocalShapeMatching3;// Offset:  276 Size:     4
//   float g_StiffnessForGlobalShapeMatching3;// Offset:  280 Size:     4 [unused]
//   float g_GlobalShapeMatchingEffectiveRange3;// Offset:  284 Size:     4 [unused]
//
// }
//
// Resource bind info for g_GuideHairVertexPositions
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for g_GlobalRotations
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_GuideHairVerticesOffsetsSRV     texture    sint         buf    0        1
// g_GuideHairStrandType             texture    sint         buf    2        1
// g_GuideHairRefVecsInLocalFrame    texture  float3         buf    3        1
// g_GuideHairVertexPositions            UAV  struct         r/w    0        1
// g_GlobalRotations                     UAV  struct         r/w    4        1
// ConstBufferCS_Per_Frame           cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[18], immediateIndexed
dcl_resource_buffer (sint,sint,sint,sint) t0
dcl_resource_buffer (sint,sint,sint,sint) t2
dcl_resource_buffer (float,float,float,float) t3
dcl_uav_structured u0, 16
dcl_uav_structured u4, 16
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadGroupID.x
dcl_temps 12
dcl_thread_group 64, 1, 1
imad r0.x, vThreadGroupID.x, l(64), vThreadIDInGroupFlattened.x
if_nz r0.x
  iadd r0.y, r0.x, l(-1)
  ld_indexable(buffer)(sint,sint,sint,sint) r0.z, r0.yyyy, t0.yzxw
  ld_indexable(buffer)(sint,sint,sint,sint) r0.y, r0.yyyy, t2.yxzw
else 
  mov r0.yz, l(0,0,0,0)
endif 
ld_indexable(buffer)(sint,sint,sint,sint) r0.x, r0.xxxx, t0.xyzw
iadd r0.x, r0.x, -r0.z
ieq r1.xyz, r0.yyyy, l(2, 3, 1, 0)
movc r0.y, r0.y, l(0), cb0[14].y
movc r0.y, r1.z, cb0[15].y, r0.y
movc r0.y, r1.y, cb0[17].y, r0.y
movc r0.y, r1.x, cb0[16].y, r0.y
min r0.y, r0.y, l(0.950000)
iadd r0.xw, r0.xxxz, l(-1, 0, 0, 1)
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.xyzw, r0.w, l(0), u0.xyzw
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyzw, r0.z, l(0), u4.xyzw
mul r0.y, r0.y, l(0.500000)
mov r3.xyzw, r2.xyzw
mov r4.xyz, r1.xyzx
mov r0.w, r1.w
mov r4.w, l(1)
loop 
  uge r5.x, r4.w, r0.x
  breakc_nz r5.x
  iadd r5.x, r0.z, r4.w
  iadd r5.y, r5.x, l(1)
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r6.xyzw, r5.y, l(0), u0.xyzw
  mul r5.z, r3.x, cb0[8].x
  mad r5.z, cb0[8].w, r3.w, -r5.z
  mad r5.z, -cb0[8].y, r3.y, r5.z
  mad r5.z, -cb0[8].z, r3.z, r5.z
  dp3 r5.w, cb0[8].wyxw, r3.xzwx
  mad r7.y, -cb0[8].z, r3.y, r5.w
  dp3 r5.w, cb0[8].zwyz, r3.xywx
  mad r7.z, -cb0[8].x, r3.z, r5.w
  dp3 r5.w, cb0[8].xwzx, r3.yzwy
  mad r7.x, -cb0[8].y, r3.x, r5.w
  ld_indexable(buffer)(float,float,float,float) r8.xyz, r5.yyyy, t3.xyzw
  mul r9.xyz, r7.xyzx, r8.yzxy
  mad r9.xyz, r7.zxyz, r8.zxyz, -r9.xyzx
  mul r10.xyz, r7.xyzx, r9.yzxy
  mad r10.xyz, r7.zxyz, r9.zxyz, -r10.xyzx
  add r5.w, r5.z, r5.z
  mad r8.xyz, r9.xyzx, r5.wwww, r8.xyzx
  mad r8.xyz, r10.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r8.xyzx
  add r8.xyz, r4.xyzx, r8.xyzx
  add r8.xyz, -r6.xyzx, r8.xyzx
  lt r5.w, l(0.000000), r0.w
  mad r9.xyz, -r0.yyyy, r8.xyzx, r4.xyzx
  movc r9.xyz, r5.wwww, r9.xyzx, r4.xyzx
  lt r5.w, l(0.000000), r6.w
  mad r8.xyz, r0.yyyy, r8.xyzx, r6.xyzx
  movc r4.xyz, r5.wwww, r8.xyzx, r6.xyzx
  dp3 r5.w, r7.xyzx, r7.xyzx
  mad r5.w, r5.z, r5.z, r5.w
  ge r6.x, r5.w, l(0.001000)
  div r7.xyz, -r7.yzxy, r5.wwww
  div r7.w, r5.z, r5.w
  movc r7.xyzw, r6.xxxx, r7.xyzw, l(0,0,0,1.000000)
  add r8.xyzw, -r9.xyzx, r4.xyzx
  dp3 r5.z, r8.yzwy, r8.yzwy
  rsq r5.z, r5.z
  mul r8.xyzw, r5.zzzz, r8.xyzw
  mul r10.xyzw, r7.zxyz, r8.yzwy
  mad r10.xyzw, r7.yzxy, r8.zwyz, -r10.xyzw
  mul r11.xyzw, r7.zxyz, r10.yzwy
  mad r11.xyzw, r7.yzxy, r10.zwyz, -r11.xyzw
  add r5.z, r7.w, r7.w
  mad r7.xyzw, r10.xyzw, r5.zzzz, r8.xyzw
  mad r7.xyzw, r11.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), r7.xyzw
  dp3 r5.z, r7.yzwy, r7.yzwy
  rsq r5.z, r5.z
  mul r7.xyzw, r5.zzzz, r7.xyzw
  mul r5.zw, r7.zzzw, l(0.000000, 0.000000, 1.000000, 0.000000)
  mad r8.xyzw, r7.xyyx, l(0.000000, 1.000000, 1.000000, 0.000000), -r5.zwwz
  dp2 r5.z, r8.zwzz, r8.zwzz
  sqrt r5.w, r5.z
  lt r5.w, l(0.001000), r5.w
  if_nz r5.w
    add r5.w, -|r7.w|, l(1.000000)
    sqrt r5.w, r5.w
    mad r6.x, |r7.w|, l(-0.018729), l(0.074261)
    mad r6.x, r6.x, |r7.w|, l(-0.212114)
    mad r6.x, r6.x, |r7.w|, l(1.570729)
    mul r6.y, r5.w, r6.x
    mad r6.y, r6.y, l(-2.000000), l(3.141593)
    lt r6.z, r7.w, -r7.w
    and r6.y, r6.z, r6.y
    mad r5.w, r6.x, r5.w, r6.y
    rsq r5.z, r5.z
    mul r7.xyzw, r5.zzzz, r8.xyzw
    mul r5.z, r5.w, l(0.500000)
    sincos r6.x, r8.x, r5.z
    mul r7.xyzw, r7.xyzw, r6.xxxx
    mul r5.zw, r3.yyyy, r7.wwwz
    mad r5.z, r3.w, r8.x, -r5.z
    mad r10.w, -r3.z, r7.z, r5.z
    mad r5.z, r3.x, r8.x, r5.w
    mad r10.x, -r3.z, r7.w, r5.z
    mul r5.zw, r3.wwww, r7.xxxz
    mad r5.zw, r3.yyyz, r8.xxxx, r5.zzzw
    mad r10.y, -r3.x, r7.y, r5.z
    mad r10.z, r3.x, r7.w, r5.w
    mov r3.xyzw, r10.xyzw
  endif 
  store_structured u0.xyz, r5.x, l(0), r9.xyzx
  store_structured u0.xyz, r5.y, l(0), r4.xyzx
  iadd r4.w, r4.w, l(1)
  mov r0.w, r6.w
endloop 
ret 
// Approximately 114 instruction slots used
