//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_5_0 /O1 /E VS_ScreenQuad shaders\Source\common.hlsl /Fo
//    Shaders\Cache\Object\Release\VS_ScreenQuad.obj /Fe
//    Shaders\Cache\Error\VS_ScreenQuad.txt /Fc
//    Shaders\Cache\Assembly\VS_ScreenQuad.asm
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyz         0     NONE  float   xyz 
// NORMAL                   0   xyz         1     NONE  float       
// TEXCOORD                 0   xy          2     NONE  float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xyzw
// TEXCOORD                 0   xy          1     NONE  float   xy  
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_input v0.xyz
dcl_input v2.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
mov o0.xyz, v0.xyzx
mov o0.w, l(1.000000)
mov o1.xy, v2.xyxx
ret 
// Approximately 4 instruction slots used
