//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /O1 /E PS_FullscreenLight Shaders\source\ShadingPasses.hlsl
//    /Fo Shaders\Cache\Object\Release\PS_FullscreenLight.obj /Fe
//    Shaders\Cache\Error\PS_FullscreenLight.txt /Fc
//    Shaders\Cache\Assembly\PS_FullscreenLight.asm
//
//
// Buffer Definitions: 
//
// cbuffer cbMain
// {
//
//   float4x4 g_mView;                  // Offset:    0 Size:    64 [unused]
//   float4x4 g_mProjection;            // Offset:   64 Size:    64 [unused]
//   float4x4 g_mViewProjection;        // Offset:  128 Size:    64 [unused]
//   float4x4 g_mInvView;               // Offset:  192 Size:    64 [unused]
//   float4x4 g_mInvViewProjectionViewport;// Offset:  256 Size:    64
//   float4x4 g_mWorld;                 // Offset:  320 Size:    64 [unused]
//   float4 g_vEye;                     // Offset:  384 Size:    16 [unused]
//   float4 g_vCameraViewVector;        // Offset:  400 Size:    16 [unused]
//   float4 g_vScreenResolution;        // Offset:  416 Size:    16 [unused]
//   float4 g_vLightPosition;           // Offset:  432 Size:    16
//   float4 g_vLightDiffuse;            // Offset:  448 Size:    16
//   float4 g_vLightAmbient;            // Offset:  464 Size:    16
//   float g_ShowDiscardedPixels;       // Offset:  480 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// txGBuffer0                        texture  float4          2d    0        1
// txGBuffer1                        texture  float4          2d    1        1
// txDepthBuffer                     texture  float4          2d    2        1
// cbMain                            cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// TEXCOORD                 0   xy          0     NONE  float       
// SV_POSITION              0   xyzw        1      POS  float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[30], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps_siv linear noperspective v1.xy, position
dcl_output o0.xyzw
dcl_temps 3
ftoi r0.xy, v1.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r1.z, r0.xyzw, t2.yzxw
mov r1.xy, v1.xyxx
mov r1.w, l(1.000000)
dp4 r2.x, r1.xyzw, cb0[16].xyzw
dp4 r2.y, r1.xyzw, cb0[17].xyzw
dp4 r2.z, r1.xyzw, cb0[18].xyzw
dp4 r0.z, r1.xyzw, cb0[19].xyzw
div r1.xyz, r2.xyzx, r0.zzzz
add r1.xyz, -r1.xyzx, cb0[27].xyzx
dp3 r0.z, r1.xyzx, r1.xyzx
rsq r1.w, r0.z
sqrt r0.z, r0.z
div r0.z, r0.z, cb0[27].w
mul r0.z, r0.z, r0.z
mad r0.z, -r0.z, r0.z, l(1.000000)
max r0.z, r0.z, l(0.000000)
mul r1.xyz, r1.wwww, r1.xyzx
ld_indexable(texture2d)(float,float,float,float) r2.xyz, r0.xyww, t1.xyzw
ld_indexable(texture2d)(float,float,float,float) r0.xyw, r0.xyww, t0.xywz
mad r2.xyz, r2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
dp3_sat r1.x, r2.xyzx, r1.xyzx
mul r1.xyz, r0.xywx, r1.xxxx
mul r0.xyw, r0.xyxw, cb0[29].xyxz
mul r1.xyz, r1.xyzx, cb0[28].xyzx
mad o0.xyz, r1.xyzx, r0.zzzz, r0.xywx
mov o0.w, l(0)
ret 
// Approximately 29 instruction slots used
