//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /O1 /E PS_FillGBuffers Shaders\source\BuildGBuffers.hlsl /Fo
//    Shaders\Cache\Object\Release\PS_FillGBuffers.obj /Fe
//    Shaders\Cache\Error\PS_FillGBuffers.txt /Fc
//    Shaders\Cache\Assembly\PS_FillGBuffers.asm
//
//
// Buffer Definitions: 
//
// cbuffer cbMain
// {
//
//   float4x4 g_mView;                  // Offset:    0 Size:    64 [unused]
//   float4x4 g_mProjection;            // Offset:   64 Size:    64 [unused]
//   float4x4 g_mViewProjection;        // Offset:  128 Size:    64 [unused]
//   float4x4 g_mInvView;               // Offset:  192 Size:    64 [unused]
//   float4x4 g_mInvViewProjectionViewport;// Offset:  256 Size:    64 [unused]
//   float4x4 g_mWorld;                 // Offset:  320 Size:    64 [unused]
//   float4 g_vEye;                     // Offset:  384 Size:    16 [unused]
//   float4 g_vCameraViewVector;        // Offset:  400 Size:    16 [unused]
//   float4 g_vScreenResolution;        // Offset:  416 Size:    16 [unused]
//   float4 g_vLightPosition;           // Offset:  432 Size:    16 [unused]
//   float4 g_vLightDiffuse;            // Offset:  448 Size:    16 [unused]
//   float4 g_vLightAmbient;            // Offset:  464 Size:    16 [unused]
//   float g_ShowDiscardedPixels;       // Offset:  480 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_samAnisotropic                  sampler      NA          NA    2        1
// g_txDiffuse                       texture  float4          2d    0        1
// g_txSpecular                      texture  float4          2d    2        1
// cbMain                            cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// TEXCOORD                 0   xy          0     NONE  float   xy  
// NORMAL                   0   xyz         1     NONE  float   xyz 
// SV_POSITION              0   xyzw        2      POS  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
// SV_TARGET                1   xyzw        1   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[1], immediateIndexed
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps linear v0.xy
dcl_input_ps linear v1.xyz
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_temps 1
sample_indexable(texture2d)(float,float,float,float) r0.xyz, v0.xyxx, t0.xyzw, s2
mov o0.xyz, r0.xyzx
sample_indexable(texture2d)(float,float,float,float) r0.x, v0.xyxx, t2.xyzw, s2
mov o0.w, r0.x
mad o1.xyz, v1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
mov o1.w, l(0)
ret 
// Approximately 7 instruction slots used
