//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /O1 /E PSConstantColor Shaders\source\Particle.hlsl /Fo
//    Shaders\Cache\Object\Release\PSConstantColor.obj /Fe
//    Shaders\Cache\Error\PSConstantColor.txt /Fc
//    Shaders\Cache\Assembly\PSConstantColor.asm
//
//
// Buffer Definitions: 
//
// cbuffer cbMain
// {
//
//   float4x4 g_mView;                  // Offset:    0 Size:    64 [unused]
//   float4x4 g_mProjection;            // Offset:   64 Size:    64 [unused]
//   float4x4 g_mViewProjection;        // Offset:  128 Size:    64 [unused]
//   float4x4 g_mInvView;               // Offset:  192 Size:    64 [unused]
//   float4x4 g_mInvViewProjectionViewport;// Offset:  256 Size:    64 [unused]
//   float4x4 g_mWorld;                 // Offset:  320 Size:    64 [unused]
//   float4 g_vEye;                     // Offset:  384 Size:    16 [unused]
//   float4 g_vCameraViewVector;        // Offset:  400 Size:    16 [unused]
//   float4 g_vScreenResolution;        // Offset:  416 Size:    16 [unused]
//   float4 g_vLightPosition;           // Offset:  432 Size:    16 [unused]
//   float4 g_vLightDiffuse;            // Offset:  448 Size:    16 [unused]
//   float4 g_vLightAmbient;            // Offset:  464 Size:    16 [unused]
//   float g_ShowDiscardedPixels;       // Offset:  480 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_samLinear                       sampler      NA          NA    0        1
// g_txDiffuse                       texture  float4          2d    0        1
// cbMain                            cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// PARTICLEPOSITION         0   xyzw        0     NONE  float       
// TEXCOORD                 0   xy          1     NONE  float   xy  
// COLOR                    0   xyzw        2     NONE  float   xyzw
// SV_POSITION              0   xyzw        3      POS  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_input_ps constant v2.xyzw
dcl_output o0.xyzw
dcl_temps 2
sample_indexable(texture2d)(float,float,float,float) r0.x, v1.xyxx, t0.wxyz, s0
mad r0.y, r0.x, v2.w, l(-0.003922)
mul r1.xyzw, r0.xxxx, v2.xyzw
mov o0.xyzw, r1.xyzw
lt r0.x, r0.y, l(0.000000)
discard r0.x
ret 
// Approximately 7 instruction slots used
