//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_5_0 /O1 /E VS_FillGBuffers Shaders\Source\BuildGBuffers.hlsl /Fo
//    Shaders\Cache\Object\Release\VS_FillGBuffers.obj /Fe
//    Shaders\Cache\Error\VS_FillGBuffers.txt /Fc
//    Shaders\Cache\Assembly\VS_FillGBuffers.asm
//
//
// Buffer Definitions: 
//
// cbuffer cbMain
// {
//
//   float4x4 g_mView;                  // Offset:    0 Size:    64 [unused]
//   float4x4 g_mProjection;            // Offset:   64 Size:    64 [unused]
//   float4x4 g_mViewProjection;        // Offset:  128 Size:    64
//   float4x4 g_mInvView;               // Offset:  192 Size:    64 [unused]
//   float4x4 g_mInvViewProjectionViewport;// Offset:  256 Size:    64 [unused]
//   float4x4 g_mWorld;                 // Offset:  320 Size:    64
//   float4 g_vEye;                     // Offset:  384 Size:    16 [unused]
//   float4 g_vCameraViewVector;        // Offset:  400 Size:    16 [unused]
//   float4 g_vScreenResolution;        // Offset:  416 Size:    16 [unused]
//   float4 g_vLightPosition;           // Offset:  432 Size:    16 [unused]
//   float4 g_vLightDiffuse;            // Offset:  448 Size:    16 [unused]
//   float4 g_vLightAmbient;            // Offset:  464 Size:    16 [unused]
//   float g_ShowDiscardedPixels;       // Offset:  480 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbMain                            cbuffer      NA          NA    0        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyz         0     NONE  float   xyz 
// NORMAL                   0   xyz         1     NONE  float   xyz 
// TEXCOORD                 0   xy          2     NONE  float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// TEXCOORD                 0   xy          0     NONE  float   xy  
// NORMAL                   0   xyz         1     NONE  float   xyz 
// SV_POSITION              0   xyzw        2      POS  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[24], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xyz
dcl_input v2.xy
dcl_output o0.xy
dcl_output o1.xyz
dcl_output_siv o2.xyzw, position
dcl_temps 2
mov o0.xy, v2.xyxx
dp3 r0.x, v1.xyzx, cb0[20].xyzx
dp3 r0.y, v1.xyzx, cb0[21].xyzx
dp3 r0.z, v1.xyzx, cb0[22].xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul o1.xyz, r0.wwww, r0.xyzx
mul r0.xyzw, cb0[9].xyzw, cb0[20].yyyy
mad r0.xyzw, cb0[8].xyzw, cb0[20].xxxx, r0.xyzw
mad r0.xyzw, cb0[10].xyzw, cb0[20].zzzz, r0.xyzw
mad r0.xyzw, cb0[11].xyzw, cb0[20].wwww, r0.xyzw
mov r1.xyz, v0.xyzx
mov r1.w, l(1.000000)
dp4 o2.x, r1.xyzw, r0.xyzw
mul r0.xyzw, cb0[9].xyzw, cb0[21].yyyy
mad r0.xyzw, cb0[8].xyzw, cb0[21].xxxx, r0.xyzw
mad r0.xyzw, cb0[10].xyzw, cb0[21].zzzz, r0.xyzw
mad r0.xyzw, cb0[11].xyzw, cb0[21].wwww, r0.xyzw
dp4 o2.y, r1.xyzw, r0.xyzw
mul r0.xyzw, cb0[9].xyzw, cb0[22].yyyy
mad r0.xyzw, cb0[8].xyzw, cb0[22].xxxx, r0.xyzw
mad r0.xyzw, cb0[10].xyzw, cb0[22].zzzz, r0.xyzw
mad r0.xyzw, cb0[11].xyzw, cb0[22].wwww, r0.xyzw
dp4 o2.z, r1.xyzw, r0.xyzw
mul r0.xyzw, cb0[9].xyzw, cb0[23].yyyy
mad r0.xyzw, cb0[8].xyzw, cb0[23].xxxx, r0.xyzw
mad r0.xyzw, cb0[10].xyzw, cb0[23].zzzz, r0.xyzw
mad r0.xyzw, cb0[11].xyzw, cb0[23].wwww, r0.xyzw
dp4 o2.w, r1.xyzw, r0.xyzw
ret 
// Approximately 30 instruction slots used
